//! Raw FFI bindings to VPP (vlib / vnet / vppinfra).
//!
//! Everything here is generated by bindgen at build time against the VPP
//! install tree found by build.rs (see `VPP_PREFIX`). Static inline
//! functions from the VPP headers are exposed through compiled C shims,
//! so calling them costs a real function call — reimplement the hot ones
//! in Rust in the `vpp` wrapper crate when it matters.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(improper_ctypes)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// va_list helpers from shim.c — VPP format/unformat callbacks receive a
// `va_list *`; Rust cannot va_arg, so these pull arguments out for us.
unsafe extern "C" {
    pub fn vppsys_va_arg_ptr(ap: *mut core::ffi::c_void) -> *mut core::ffi::c_void;
    pub fn vppsys_va_arg_u32(ap: *mut core::ffi::c_void) -> u32;
    pub fn vppsys_va_arg_uword(ap: *mut core::ffi::c_void) -> u64;
}
